### ISSUE TITLE
README.MD Tutorial is different from actual use in Nuget version 2.0.0

### ISSUE THREAD

**Issue by JeffBusterCase** [Nyerst/FastGenericNew#14]

**Comment by Nyerst** [comment]
Hi, thanks for the comment.

It's because the README is currently targeted to the 3.0.0 preview version.
I just changed the README title to FastGenericNew 3.0.0 to avoid ambiguity.

You can install 3.0.0 version by following instructions:
https://github.com/Nyerst/FastGenericNew#installation

However, the 2.0.0 tutorial is still available at the 2.0.x branch:
https://github.com/Nyerst/FastGenericNew/tree/2.0.x

**Comment by JeffBusterCase** [comment]
Ok thanks
